let demoBlogData = [
    {
      id: 1,
      title: "Introduction to JavaScript",
      content: "This is a demo post about JavaScript basics. JavaScript is a versatile language for web development.",
      author: "John Doe",
      created_at: "2025-02-16T10:00:00Z",
      updated_at: "2025-02-16T12:00:00Z",
      category: "Programming",
    },
    {
      id: 2,
      title: "Getting Started with HTML",
      content: "Learn the basics of HTML to structure your webpages. HTML is the backbone of web development.",
      author: "Jane Smith",
      created_at: "2025-02-15T08:00:00Z",
      updated_at: "2025-02-15T09:00:00Z",
      category: "Web Development",
    },
    {
      id: 3,
      title: "Understanding CSS Grid",
      content: "CSS Grid is a powerful tool for creating flexible and responsive web layouts. It makes designing complex layouts easier.",
      author: "Alice Johnson",
      created_at: "2025-02-14T13:30:00Z",
      updated_at: "2025-02-14T14:00:00Z",
      category: "Web Design",
    },
    {
      id: 4,
      title: "Introduction to Node.js",
      content: "Node.js allows you to run JavaScript on the server side. It has become a popular tool for building scalable applications.",
      author: "Bob Brown",
      created_at: "2025-02-13T10:00:00Z",
      updated_at: "2025-02-13T11:00:00Z",
      category: "Backend Development",
    },
    {
      id: 5,
      title: "JavaScript ES6 Features",
      content: "ES6 introduced many features like arrow functions, promises, and destructuring that make JavaScript programming more efficient.",
      author: "Eve Davis",
      created_at: "2025-02-12T16:00:00Z",
      updated_at: "2025-02-12T17:00:00Z",
      category: "Programming",
    },
    {
      id: 6,
      title: "Web Accessibility Best Practices",
      content: "Web accessibility ensures that websites can be used by everyone, including people with disabilities. Learn the best practices for inclusive design.",
      author: "Charlie Green",
      created_at: "2025-02-11T09:30:00Z",
      updated_at: "2025-02-11T10:00:00Z",
      category: "Web Design",
    },
    {
      id: 7,
      title: "Intro to Version Control with Git",
      content: "Git is a distributed version control system that helps track changes in code. Learn how to use Git for versioning your projects.",
      author: "Daniel Lee",
      created_at: "2025-02-10T11:00:00Z",
      updated_at: "2025-02-10T12:00:00Z",
      category: "Development Tools",
    },
    {
      id: 8,
      title: "Building RESTful APIs with Express",
      content: "Express.js is a minimal web framework for Node.js that simplifies the process of building RESTful APIs.",
      author: "Grace Kim",
      created_at: "2025-02-09T14:30:00Z",
      updated_at: "2025-02-09T15:00:00Z",
      category: "Backend Development",
    },
    {
      id: 9,
      title: "Responsive Web Design with Bootstrap",
      content: "Bootstrap is a popular front-end framework that helps in creating responsive web pages quickly using pre-designed components.",
      author: "Henry White",
      created_at: "2025-02-08T12:00:00Z",
      updated_at: "2025-02-08T13:00:00Z",
      category: "Web Design",
    },
    {
      id: 10,
      title: "Understanding Asynchronous JavaScript",
      content: "Asynchronous programming in JavaScript is essential for handling operations like API calls without blocking the user interface.",
      author: "Ivy Black",
      created_at: "2025-02-07T15:00:00Z",
      updated_at: "2025-02-07T16:00:00Z",
      category: "Programming",
    },
  ];


  export default demoBlogData;
  
